;;; swiftui-preview-core.el --- Core SwiftUI preview utilities -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Mikael Konradsson
;; Author: Mikael Konradsson
;; Version: 0.6.0
;; Package-Requires: ((emacs "28.1"))
;; URL: https://github.com/konrad1977/swift-development
;; Keywords: swift, swiftui, preview, ios

;;; Commentary:

;; Core utilities shared between swiftui-preview-dynamic.el and
;; swiftui-preview-spm.el.  This module provides:
;; - PreviewHostApp Swift code generation
;; - Simulator interaction (find, boot, install, launch)
;; - Preview capture with transparent background
;; - Common helper functions

;;; Code:

(require 'cl-lib)
(require 'json)
(require 'swift-async nil t)

;; Forward declarations
(declare-function ios-simulator-simulator-identifier "ios-simulator")
(declare-function swift-async-run-sync "swift-async")

;;; Customization

(defgroup swiftui-preview-core nil
  "Core SwiftUI preview settings."
  :group 'swiftui-preview
  :prefix "swiftui-preview-core-")

(defcustom swiftui-preview-core-default-simulator "iPhone 16 Pro"
  "Default simulator name for previews."
  :type 'string
  :group 'swiftui-preview-core)

(defcustom swiftui-preview-core-capture-timeout 10.0
  "Timeout in seconds for preview capture."
  :type 'number
  :group 'swiftui-preview-core)

(defcustom swiftui-preview-core-verbose nil
  "If non-nil, show verbose output during preview generation."
  :type 'boolean
  :group 'swiftui-preview-core)

;;; Internal variables

(defvar swiftui-preview-core--scripts-dir
  (expand-file-name "scripts" (file-name-directory (or load-file-name buffer-file-name)))
  "Directory containing Ruby helper scripts.")

;;; Swift Code Generation

(defconst swiftui-preview-core--snapshot-code
  "
// MARK: - Snapshot Logic

func snapshotPreview() {
    let previewView = PreviewContent()
    
    let hostingController = UIHostingController(rootView: previewView.fixedSize())
    let targetSize = hostingController.sizeThatFits(in: CGSize(width: CGFloat.infinity, height: CGFloat.infinity))
    
    let padding: CGFloat = 40
    let finalSize = CGSize(
        width: targetSize.width + padding * 2,
        height: targetSize.height + padding * 2
    )
    
    let paddedView = previewView
        .fixedSize()
        .padding(padding)
        .frame(width: finalSize.width, height: finalSize.height, alignment: .center)
        .background(Color.clear)
    
    let finalController = UIHostingController(rootView: paddedView)
    finalController.view.frame = CGRect(origin: .zero, size: finalSize)
    finalController.view.backgroundColor = .clear
    finalController.view.layoutIfNeeded()
    
    let format = UIGraphicsImageRendererFormat()
    format.scale = UIScreen.main.scale
    format.opaque = false
    
    let renderer = UIGraphicsImageRenderer(size: finalSize, format: format)
    let image = renderer.image { context in
        finalController.view.drawHierarchy(in: CGRect(origin: .zero, size: finalSize), afterScreenUpdates: true)
    }
    
    guard let data = image.pngData() else {
        print(\"ERROR: Failed to create PNG data\")
        exit(1)
    }
    
    let outputPath = ProcessInfo.processInfo.environment[\"PREVIEW_OUTPUT_PATH\"] 
        ?? \"/tmp/swift-development-preview.png\"
    
    let url = URL(fileURLWithPath: outputPath)
    try? FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    
    do {
        try data.write(to: url)
        print(\"Preview saved to: \\(outputPath)\")
    } catch {
        print(\"ERROR: \\(error)\")
        exit(1)
    }
    
    exit(0)
}
"
  "Swift code for snapshot functionality.")

(defun swiftui-preview-core-generate-host-app (preview-body imports &optional filename)
  "Generate PreviewHostApp.swift content.
PREVIEW-BODY is the extracted #Preview content.
IMPORTS is list of modules to import.
FILENAME is optional source file name for comment."
  (let* ((fname (or filename "SwiftUI Preview"))
         (import-statements (mapconcat (lambda (imp) (format "import %s" imp))
                                       imports "\n"))
         (indented-body (replace-regexp-in-string
                         "^" "            "
                         preview-body)))
    (format "// Auto-generated PreviewHost for %s
// Generated by swift-development

%s
import UIKit

@main
struct PreviewHostApp: App {
    var body: some Scene {
        WindowGroup {
            PreviewContent()
                .onAppear {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                        snapshotPreview()
                    }
                }
        }
    }
}

struct PreviewContent: View {
    var body: some View {
%s
    }
}
%s" fname import-statements indented-body swiftui-preview-core--snapshot-code)))

(defun swiftui-preview-core-write-host-app (preview-body imports temp-dir &optional filename)
  "Write PreviewHostApp.swift to TEMP-DIR.
PREVIEW-BODY is the extracted #Preview content.
IMPORTS is list of modules to import.
FILENAME is optional source file name for comment.
Returns path to written file."
  (let ((host-content (swiftui-preview-core-generate-host-app preview-body imports filename))
        (host-file (expand-file-name "PreviewHostApp.swift" temp-dir)))
    (make-directory temp-dir t)
    (with-temp-file host-file
      (insert host-content))
    (when swiftui-preview-core-verbose
      (message "[Preview Core] Generated PreviewHost in %s" temp-dir))
    host-file))

;;; Import Extraction

(defun swiftui-preview-core-extract-imports ()
  "Extract all import statements from current buffer.
Returns a list of imported module names."
  (save-excursion
    (goto-char (point-min))
    (let ((imports '()))
      (while (re-search-forward "^import[[:space:]]+\\([A-Za-z_][A-Za-z0-9_]*\\)" nil t)
        (push (match-string 1) imports))
      (delete-dups (nreverse imports)))))

;;; Simulator Interaction

(defun swiftui-preview-core--simctl (args)
  "Run simctl with ARGS synchronously.
Returns output string on success, nil on failure."
  (if (fboundp 'swift-async-run-sync)
      (swift-async-run-sync (append '("xcrun" "simctl") args) :timeout 10)
    (with-temp-buffer
      (when (zerop (apply #'call-process "xcrun" nil t nil "simctl" args))
        (buffer-string)))))

(defun swiftui-preview-core-find-simulator (&optional preferred-name)
  "Find simulator UDID to use for preview.
PREFERRED-NAME is the preferred simulator name.
Tries: ios-simulator selection, preferred name, first booted."
  (or
   ;; Try ios-simulator if available
   (and (fboundp 'ios-simulator-simulator-identifier)
        (ios-simulator-simulator-identifier))
   ;; Try to find by name
   (when-let* ((name (or preferred-name swiftui-preview-core-default-simulator))
               (script (expand-file-name "preview-helper.rb" swiftui-preview-core--scripts-dir))
               (output (shell-command-to-string
                        (format "ruby %s find-simulator %s 2>/dev/null"
                                (shell-quote-argument script)
                                (shell-quote-argument name))))
               (udid (string-trim output)))
     (unless (string-empty-p udid) udid))
   ;; Try first booted
   (when-let* ((script (expand-file-name "preview-helper.rb" swiftui-preview-core--scripts-dir))
               (output (shell-command-to-string
                        (format "ruby %s first-booted 2>/dev/null"
                                (shell-quote-argument script))))
               (udid (string-trim output)))
     (unless (string-empty-p udid) udid))))

(defun swiftui-preview-core-ensure-simulator-booted (udid)
  "Ensure simulator with UDID is booted."
  (let* ((json-array-type 'list)  ; Parse JSON arrays as lists, not vectors
         (json-output (if (fboundp 'swift-async-run-sync)
                          (swift-async-run-sync
                           '("xcrun" "simctl" "list" "devices" "-j")
                           :timeout 5 :parse-json t)
                        (condition-case nil
                            (json-read-from-string
                             (shell-command-to-string
                              "xcrun simctl list devices -j 2>/dev/null"))
                          (error nil)))))
    (when json-output
      (let ((booted nil))
        (catch 'found
          (dolist (runtime (alist-get 'devices json-output))
            ;; Handle both list and vector device arrays
            (let ((devices (cdr runtime)))
              (when (vectorp devices)
                (setq devices (append devices nil)))
              (dolist (device devices)
                (when (and (equal (alist-get 'udid device) udid)
                           (equal (alist-get 'state device) "Booted"))
                  (setq booted t)
                  (throw 'found t))))))
        (unless booted
          (message "Booting simulator...")
          (swiftui-preview-core--simctl (list "boot" udid))
          (sleep-for 2))))))

;;; Preview Capture

(defun swiftui-preview-core-capture (app-path simulator-udid output-path bundle-id)
  "Install APP-PATH, launch, and wait for internal snapshot.
SIMULATOR-UDID is the target simulator.
OUTPUT-PATH is where the preview image will be saved.
BUNDLE-ID is the app's bundle identifier.
Returns OUTPUT-PATH on success."
  (let ((process-environment (cons (format "SIMCTL_CHILD_PREVIEW_OUTPUT_PATH=%s" output-path)
                                   process-environment)))
    
    ;; Terminate any existing instance
    (swiftui-preview-core--simctl (list "terminate" simulator-udid bundle-id))
    
    ;; Ensure output directory exists and remove old file
    (make-directory (file-name-directory output-path) t)
    (when (file-exists-p output-path)
      (delete-file output-path))
    
    ;; Install
    (message "Installing preview app...")
    (unless (swiftui-preview-core--simctl (list "install" simulator-udid app-path))
      (error "Failed to install preview app"))
    
    ;; Launch
    (message "Launching preview app...")
    (swiftui-preview-core--simctl (list "launch" simulator-udid bundle-id))
    
    ;; Wait for the app to generate the preview and exit
    (message "Waiting for preview generation...")
    (let ((timeout swiftui-preview-core-capture-timeout)
          (poll-interval 0.2)
          (elapsed 0.0))
      (while (and (< elapsed timeout)
                  (not (file-exists-p output-path)))
        (sleep-for poll-interval)
        (setq elapsed (+ elapsed poll-interval)))
      
      (unless (file-exists-p output-path)
        ;; Fallback: try simctl screenshot
        (message "Internal capture timed out, falling back to screenshot...")
        (swiftui-preview-core--simctl
         (list "io" simulator-udid "screenshot" output-path))))
    
    ;; Terminate app
    (swiftui-preview-core--simctl (list "terminate" simulator-udid bundle-id))
    
    (if (file-exists-p output-path)
        output-path
      (error "Failed to generate preview"))))

;;; Ruby Script Helpers

(defun swiftui-preview-core-run-ruby-script (script-name &rest args)
  "Run Ruby script SCRIPT-NAME with ARGS.
Returns parsed JSON result or signals error."
  (let* ((script (expand-file-name script-name swiftui-preview-core--scripts-dir))
         (cmd (mapconcat #'shell-quote-argument (cons "ruby" (cons script args)) " "))
         (output (shell-command-to-string (concat cmd " 2>&1")))
         (json-output nil))
    
    (when swiftui-preview-core-verbose
      (message "[Preview Core] Running: %s" cmd))
    
    (condition-case nil
        (setq json-output (json-read-from-string output))
      (error
       (when swiftui-preview-core-verbose
         (message "[Preview Core] Script output: %s" output))
       nil))
    
    (if (and json-output (eq (alist-get 'success json-output) t))
        json-output
      (let ((error-msg (or (alist-get 'error json-output) output)))
        (error "Ruby script failed: %s" error-msg)))))

(provide 'swiftui-preview-core)
;;; swiftui-preview-core.el ends here
